Document: brann-artwork
Title: Debian brann-artwork Manual
Author: <insert document author here>
Abstract: This manual describes what brann-artwork is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/brann-artwork/brann-artwork.sgml.gz

Format: postscript
Files: /usr/share/doc/brann-artwork/brann-artwork.ps.gz

Format: text
Files: /usr/share/doc/brann-artwork/brann-artwork.text.gz

Format: HTML
Index: /usr/share/doc/brann-artwork/html/index.html
Files: /usr/share/doc/brann-artwork/html/*.html
